version: '3'

services:
  bot:
    image: blurplefy
    command: python -m bot
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./:/app
    environment:
      - JISHAKU_HIDE=true

  worker:
    image: blurplefy
    command: python -m worker
    restart: unless-stopped
    depends_on:
      - redis
    volumes:
      - ./:/app

  redis:
    image: redis:5-alpine
    command: redis-server --appendonly yes
    volumes:
      - redis:/data

volumes:
  redis:
